### ISSUE TITLE
CSV2REC - Error: The Application Was Unable To Start Correctly (0xc000007b) 

### ISSUE THREAD

**Issue by hellishvictor** [pfmoore/gnuwin64#1]
Hi, the following executables shows a 0xc000007b error:
csv2rec, rec2csv, recdel.exe, recfix.exe, recfmt.exe, recinf.exe, recins.exe, recsel.exe and recset.exe.

Cheers.

**Comment by pfmoore** [comment]
Sorry, these binaries are no longer supported. They do work for me, for what it's worth.
